### PR TITLE
Fix invalid dates being allowed by add appointment command

### LINKED ISSUE #184: [PE-D][Tester B] Bug: Invalid dates in apt command are improperly handled
## Bug Description
The `apt` command does not strictly validate inputs. It silently coerces invalid dates (e.g. `30-02-2026`) into valid ones (e.g. `28-02-2026`) instead of rejecting the input with an error message

### Actual Behavior
When a user inputs impossible/non-existent dates like `30-02-2026`, the system silently accepts the inputs and adjusts the date to the nearest valid day `28-02-2026` without notifying the user.

### Expected Behavior
The system should reject non-existent dates and display an error message prompting the user to enter a valid date.

## Impact
This is a potentially problematic behavior, as it assumes the user's intent rather than flagging the erroneous input. Implementing strict parsing rules is a good way to improve the product, as it will enhance data integrity and prevent silent scheduling failures.

## Steps to Reproduce
1. Add a appointment with a impossible date to a patient with `apt 3 d/30-02-2026 14:00 dur/30 note/Routine Checkup`
2. Observe that the system accepts the impossible date `30-02-2026 14:00` and silently reverts it to `28-02-2026`

Other similar impossible dates that can be used to achieve a similar outcome
- `apt 3 d/31-04-2026 14:00 dur/30 note/Routine Checkup` (e.g. 31 April 2026)
- `apt 3 d/31-09-2026 14:00 dur/30 note/Routine Checkup` (e.g. 31 Sep 2026)

### Screenshots
1. Before adding an appointment to `Charlotte Oliveiro`
Image

2. After adding an appointment to `Charlotte Oliveiro`, observe that the input date of `31-02-2026 14:00` has been accepted and silently defaulted to `28-02-2026 14:00`
Image

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #282: Bug: Datetime might accept `24:00`

### PR DESCRIPTION
**Pull request by alieron**
Fixes #184

### CODE REVIEW

**Comment by alieron** [comment]
Yet to add new testcases, but this will resolve the bug.

File: src/main/java/doctorwho/model/patient/Appointment.java [hunk 1]
```diff
@@ -16,16 +17,17 @@
 public class Appointment {
 
     public static final String STARTTIME_CONSTRAINTS =
-            "Appointments should have a start time in 'dd-MM-yyyy HH:mm' format";
+            "Appointments should be a valid date have a start time in 'dd-MM-yyyy HH:mm' format";
```
Comment (s6r6k) [inline src/main/java/doctorwho/model/patient/Appointment.java]: i think this should be "should be a valid date and have a start time" pls

**Review by s6r6k — COMMENTED** [review]
Image
Okay it doesnt take invalid dates anymore. 
Also i just realised we do take in past dates for appointment do we wanna change it to take dates from only today and onwards? 
An appointment from 1+ month back:

Image

**Review by s6r6k — CHANGES_REQUESTED** [review]

**Comment by alieron** [comment]
I believe in another issue, we discussed that we will allow the adding of past dates as a means of retroactive tracking. So combined with support for multiple appointments, this will improve transitions from other systems onto ours.

**Review by s6r6k — APPROVED** [review]
