### PR TITLE
Changes messages to users from "address book" to "patient book". Also change exit message from "Exiting Address Book" to "Exiting Doctor Who"

### LINKED ISSUE #219: [PE-D][Tester A] App messages still refer to database as "AddressBook"
Several user-facing messages within the application use the term "AddressBook" to refer to the patient database. This is inaccurate to the app's actual purpose and may confuse users who expect terminology consistent with a medical records system. All references to "AddressBook" in user-facing output should be updated to reflect the correct domain language.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`

### LINKED ISSUE #223: [PE-D][Tester D] Clear command still writes Address Book
Slightly inconsistent, should write DoctorWho

Image

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`

### LINKED ISSUE #256: Bug: Messages still make references to AddressBook
This consolidates several related bug reports.

### PR DESCRIPTION
**Pull request by KenOKK3003**
Fixes #256
LOC 5

Subissues:
FIxes #223 
Fixes #219

### CODE REVIEW

File: src/main/java/doctorwho/logic/commands/ExitCommand.java [hunk 1]
```diff
@@ -9,7 +9,7 @@ public class ExitCommand extends Command {
 
     public static final String COMMAND_WORD = "exit";
 
-    public static final String MESSAGE_EXIT_ACKNOWLEDGEMENT = "Exiting Address Book as requested ...";
+    public static final String MESSAGE_EXIT_ACKNOWLEDGEMENT = "Exiting Doctor Who as requested ...";
```
Comment (alieron) [inline src/main/java/doctorwho/logic/commands/ExitCommand.java]: DoctorWho shouldn't have a space.

**Review by alieron — CHANGES_REQUESTED** [review]
One small change.

File: src/main/java/doctorwho/logic/commands/ExitCommand.java (hunk 1 above)
Comment (KenOKK3003) [reply src/main/java/doctorwho/logic/commands/ExitCommand.java]: Done!

**Review by alieron — APPROVED** [review]
LGTM
